name: Build docs

on:
  push:
    paths:
      - '**.md'
      - '.github/workflows/docs.yml'
    tags:
      - '*'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
      
jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: '3.11'
          cache: true
      - name: Build pages
        run: |
          pdm install -G docs -d
          pdm run pytest
          cd docs && pdm run mkdocs build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
